### ISSUE TITLE
utf-8 char broke script

### ISSUE THREAD

**Issue by drJeckyll** [Trellmor/bind-adblock#14]
List: https://hosts-file.net/ad_servers.txt have a utf-8 char which broke script with error:
```
Traceback (most recent call last):
  File "./update-zonefile.py", line 229, in <module>
    domains = parse_lists(args.origin)
  File "./update-zonefile.py", line 135, in parse_lists
    data = download_list(l['url'])
  File "./update-zonefile.py", line 115, in download_list
    return f.read()
  File "/usr/lib/python-exec/python3.6/../../../lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc9 in position 297767: ordinal not in range(128)
```

Python is not my stenght, but replacing:
`with cache.open() as f:` with `with cache.open('r', 1, 'utf-8') as f:`
fixed error for me

**Comment by Trellmor** [comment]
Not sure what went wrong because I can't find any non ascii chars in https://hosts-file.net/ad_servers.txt. But you are right, since the cache file is written as UTF-8 it should also be read as UTF-8, even if the system has another default encoding.

Thanks!
