### ISSUE TITLE
TypeError: object doesn't support attribute assignment

### ISSUE THREAD

**Issue by finchbeast** [Trellmor/bind-adblock#22]
This might be an end user issue, but I'm not able to get the script to work. Details included below. I've swapped my actual domain name for "example.com" but I am not using "example.com" in any of my actual configuration.

```
root@server:/tmp/bind-adblock# pip3 list | grep requests
requests               2.22.0
root@server:/tmp/bind-adblock# pip3 list | grep dnspython
dnspython              2.0.0
```

```
root@server:/etc/bind# cat named.conf.options
options {
        directory "/var/cache/bind";
        auth-nxdomain no;
        // listen-on-v6 { any; };
        listen-on port 53 { localhost; 192.168.100.0/24; };
        allow-query { localhost; 192.168.100.0/24; };
        forwarders { 10.8.8.1; 192.168.1.1; };
        recursion yes;
        response-policy {
                zone "rpz.example.com";
        };
};
```

```
root@server:/etc/bind# cat named.conf.local
zone    "example.com"  {
        type master;
        file    "/etc/bind/forward.example.com";
};


zone    "100.168.192.in-addr.arpa"       {
        type master;
        file    "/etc/bind/reverse.example.com";
};


zone    "rpz.example.com"      {
        type master;
        file    "/etc/bind/rpz.example.com";
        masterfile-format text;
        allow-query { none; };
};
```

```
root@server:/etc/bind# cat rpz.example.com
@ 3600 IN SOA @ example.com. 0 86400 7200 2592000 86400
@ 3600 IN NS ns.example.com.
```

Actually running the script:
```
root@server:/tmp/bind-adblock# ./update-zonefile.py /etc/bind/rpz.example.com rpz.example.com
Traceback (most recent call last):
  File "./update-zonefile.py", line 263, in <module>
    update_serial(zone)
  File "./update-zonefile.py", line 224, in update_serial
    soa.serial += 1
  File "/usr/local/lib/python3.8/dist-packages/dns/rdata.py", line 129, in __setattr__
    raise TypeError("object doesn't support attribute assignment")
TypeError: object doesn't support attribute assignment
```

**Comment by Trellmor** [comment]
dnspython made rdata immutable in version 2.0.0. If you can, downgrade to 1.16.0 for now `pip install dnspython==1.16.0`

**Comment by finchbeast** [comment]
That did it, thanks!

**Comment by Trellmor** [comment]
Should now work with dnspython 1.16.0 and 2.0.0
