### ISSUE TITLE
issue with: FROM python:latest

### ISSUE THREAD

**Issue by Madchristian** [Trellmor/bind-adblock#42]
```
>  => ERROR [adblock 8/9] RUN pip install --upgrade pip &&     pip install -r requirements.txt                                                                                                               8.6s
> ------
>  > [adblock 8/9] RUN pip install --upgrade pip &&     pip install -r requirements.txt:
> 1.823 Requirement already satisfied: pip in /opt/venv/lib/python3.12/site-packages (24.0)
> 2.919 Collecting certifi==2022.12.7 (from -r requirements.txt (line 1))
> 3.036   Downloading certifi-2022.12.7-py3-none-any.whl.metadata (2.9 kB)
> 3.277 Collecting charset-normalizer==3.0.1 (from -r requirements.txt (line 2))
> 3.295   Downloading charset_normalizer-3.0.1-py3-none-any.whl.metadata (27 kB)
> 3.439 Collecting decorator==5.1.1 (from -r requirements.txt (line 3))
> 3.452   Downloading decorator-5.1.1-py3-none-any.whl.metadata (4.0 kB)
> 3.574 Collecting dnspython==2.3.0 (from -r requirements.txt (line 4))
> 3.589   Downloading dnspython-2.3.0-py3-none-any.whl.metadata (5.2 kB)
> 3.721 Collecting idna==3.4 (from -r requirements.txt (line 5))
> 3.739   Downloading idna-3.4-py3-none-any.whl.metadata (9.8 kB)
> 3.981 Collecting pathlib==1.0.1 (from -r requirements.txt (line 6))
> 4.000   Downloading pathlib-1.0.1-py3-none-any.whl.metadata (5.1 kB)
> 4.168 Collecting PyYAML==6.0 (from -r requirements.txt (line 7))
> 4.190   Downloading PyYAML-6.0.tar.gz (124 kB)
> 4.290      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 1.2 MB/s eta 0:00:00
> 4.384   Installing build dependencies: started
> 8.081   Installing build dependencies: finished with status 'done'
> 8.082   Getting requirements to build wheel: started
> 8.299   Getting requirements to build wheel: finished with status 'error'
> 8.305   error: subprocess-exited-with-error
> 8.305   
> 8.305   × Getting requirements to build wheel did not run successfully.
> 8.305   │ exit code: 1
> 8.305   ╰─> [54 lines of output]
> 8.305       running egg_info
> 8.305       writing lib/PyYAML.egg-info/PKG-INFO
> 8.305       writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
> 8.305       writing top-level names to lib/PyYAML.egg-info/top_level.txt
> 8.305       Traceback (most recent call last):
> 8.305         File "/opt/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
> 8.305           main()
> 8.305         File "/opt/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
> 8.305           json_out['return_val'] = hook(**hook_input['kwargs'])
> 8.305                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 8.305         File "/opt/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
> 8.305           return hook(config_settings)
> 8.305                  ^^^^^^^^^^^^^^^^^^^^^
> 8.305         File "/tmp/pip-build-env-wa0przg1/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
> 8.305           return self._get_build_requires(config_settings, requirements=['wheel'])
> 8.305                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 8.305         File "/tmp/pip-build-env-wa0przg1/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
> 8.305           self.run_setup()
> 8.305         File "/tmp/pip-build-env-wa0przg1/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
> 8.305           exec(code, locals())
> 8.305         File "<string>", line 288, in <module>
> 8.305         File "/tmp/pip-build-env-wa0przg1/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 104, in setup
> 8.305           return distutils.core.setup(**attrs)
> 8.305                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 8.305         File "/tmp/pip-build-env-wa0przg1/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
> 8.305           return run_commands(dist)
> 8.305                  ^^^^^^^^^^^^^^^^^^
> 8.305         File "/tmp/pip-build-env-wa0przg1/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
> 8.305           dist.run_commands()
> 8.305         File "/tmp/pip-build-env-wa0przg1/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
> 8.305           self.run_command(cmd)
> 8.305         File "/tmp/pip-build-env-wa0przg1/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
> 8.305           super().run_command(command)
> 8.305         File "/tmp/pip-build-env-wa0przg1/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
> 8.305           cmd_obj.run()
> 8.305         File "/tmp/pip-build-env-wa0przg1/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 321, in run
> 8.305           self.find_sources()
> 8.305         File "/tmp/pip-build-env-wa0przg1/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
> 8.305           mm.run()
> 8.305         File "/tmp/pip-build-env-wa0przg1/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 550, in run
> 8.305           self.add_defaults()
> 8.305         File "/tmp/pip-build-env-wa0przg1/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults
> 8.305           sdist.add_defaults(self)
> 8.305         File "/tmp/pip-build-env-wa0przg1/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line 102, in add_defaults
> 8.305           super().add_defaults()
> 8.305         File "/tmp/pip-build-env-wa0przg1/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
> 8.305           self._add_defaults_ext()
> 8.305         File "/tmp/pip-build-env-wa0przg1/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
> 8.305           self.filelist.extend(build_ext.get_source_files())
> 8.305                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 8.305         File "<string>", line 204, in get_source_files
> 8.305         File "/tmp/pip-build-env-wa0przg1/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
> 8.305           raise AttributeError(attr)
> 8.305       AttributeError: cython_sources
> 8.305       [end of output]
> 8.305   
> 8.305   note: This error originates from a subprocess, and is likely not a problem with pip.
> 8.307 error: subprocess-exited-with-error
> 8.307 
> 8.307 × Getting requirements to build wheel did not run successfully.
> 8.307 │ exit code: 1
> 8.307 ╰─> See above for output.
> 8.307 
> 8.307 note: This error originates from a subprocess, and is likely not a problem with pip.
> ------
> failed to solve: process "/bin/sh -c pip install --upgrade pip &&     pip install -r requirements.txt" did not complete successfully: exit code: 1
```

had to change to FROM python: 3.11

**Comment by juankhazad** [comment]
Reproductible on Ubuntu 24.04 with Python 3.12.3
